# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The blog of Roy T.
email: roy-t@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 Past: Tomb Raider (Nixxes), R.E.I.S. (Abbey Games). Current: SilverFit. MSc from Utrecht University (Cum Laude, 2014).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://roy-t.nl" # the base hostname & protocol for your site
twitter_username: roytries
github_username:  roy-t

highlighter: rouge

# Build settings
markdown: kramdown
