name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3.8.6 /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/_site
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: site      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.roy-t.nl
          username: roytnl
          password: ${{ secrets.ftppassword }}
          server-dir: domains/roy-t.nl/public_html/
